# Generated by Django 5.1.5 on 2025-09-10 03:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0003_remove_historicalindicator_category_product_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ExpenseCategory',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('state', models.BooleanField(default=True, verbose_name='Estado')),
                ('created_date', models.DateField(auto_now_add=True, verbose_name='Fecha de Creacion')),
                ('modify_date', models.DateField(auto_now=True, verbose_name='Fecha de Modificacion')),
                ('delete_data', models.DateField(auto_now=True, verbose_name='Fecha de Eliminacion')),
                ('name', models.CharField(max_length=100, verbose_name='Nombre de Categoría de Gasto')),
            ],
            options={
                'verbose_name': 'Categoria de Gasto',
                'verbose_name_plural': 'Categorias de Gastos',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='PaymentType',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('state', models.BooleanField(default=True, verbose_name='Estado')),
                ('created_date', models.DateField(auto_now_add=True, verbose_name='Fecha de Creacion')),
                ('modify_date', models.DateField(auto_now=True, verbose_name='Fecha de Modificacion')),
                ('delete_data', models.DateField(auto_now=True, verbose_name='Fecha de Eliminacion')),
                ('name', models.CharField(max_length=100, verbose_name='Nombre de Medio de Pago')),
            ],
            options={
                'verbose_name': 'Medio de Pago',
                'verbose_name_plural': 'Medio de Pagos',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Provider',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('state', models.BooleanField(default=True, verbose_name='Estado')),
                ('created_date', models.DateField(auto_now_add=True, verbose_name='Fecha de Creacion')),
                ('modify_date', models.DateField(auto_now=True, verbose_name='Fecha de Modificacion')),
                ('delete_data', models.DateField(auto_now=True, verbose_name='Fecha de Eliminacion')),
                ('ruc', models.CharField(max_length=11, unique=True)),
                ('business_name', models.CharField(max_length=150, unique=True, verbose_name='Razón Social')),
                ('address', models.CharField(max_length=200)),
                ('phone', models.CharField(blank=True, max_length=15, null=True)),
                ('email', models.EmailField(max_length=254, null=True)),
            ],
            options={
                'verbose_name': 'Proveedor',
                'verbose_name_plural': 'Proveedores',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('state', models.BooleanField(default=True, verbose_name='Estado')),
                ('created_date', models.DateField(auto_now_add=True, verbose_name='Fecha de Creacion')),
                ('modify_date', models.DateField(auto_now=True, verbose_name='Fecha de Modificacion')),
                ('delete_data', models.DateField(auto_now=True, verbose_name='Fecha de Eliminacion')),
                ('ruc', models.CharField(max_length=11, unique=True)),
                ('business_name', models.CharField(max_length=150, unique=True, verbose_name='Razón Social')),
                ('address', models.CharField(max_length=200)),
                ('phone', models.CharField(blank=True, max_length=15, null=True)),
                ('email', models.EmailField(max_length=254, null=True)),
            ],
            options={
                'verbose_name': 'Proveedor',
                'verbose_name_plural': 'Proveedores',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Voucher',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('state', models.BooleanField(default=True, verbose_name='Estado')),
                ('created_date', models.DateField(auto_now_add=True, verbose_name='Fecha de Creacion')),
                ('modify_date', models.DateField(auto_now=True, verbose_name='Fecha de Modificacion')),
                ('delete_data', models.DateField(auto_now=True, verbose_name='Fecha de Eliminacion')),
                ('name', models.CharField(max_length=100, verbose_name='Nombre de comprobante de Pago')),
            ],
            options={
                'verbose_name': 'Comprobante',
                'verbose_name_plural': 'Comprobantes',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Merma',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('state', models.BooleanField(default=True, verbose_name='Estado')),
                ('created_date', models.DateField(auto_now_add=True, verbose_name='Fecha de Creacion')),
                ('modify_date', models.DateField(auto_now=True, verbose_name='Fecha de Modificacion')),
                ('delete_data', models.DateField(auto_now=True, verbose_name='Fecha de Eliminacion')),
                ('date', models.DateField(verbose_name='Fecha de emisión de Merma')),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=7, verbose_name='Cantidad')),
                ('lost_money', models.DecimalField(decimal_places=2, max_digits=7, verbose_name='Dinero perdido')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.product')),
            ],
            options={
                'verbose_name': 'Merma',
                'verbose_name_plural': 'Mermas',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('state', models.BooleanField(default=True, verbose_name='Estado')),
                ('created_date', models.DateField(auto_now_add=True, verbose_name='Fecha de Creacion')),
                ('modify_date', models.DateField(auto_now=True, verbose_name='Fecha de Modificacion')),
                ('delete_data', models.DateField(auto_now=True, verbose_name='Fecha de Eliminacion')),
                ('date', models.DateField(verbose_name='Fecha de emisión de factura')),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Cantidad')),
                ('unit_price', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Precio Unitario')),
                ('voucher_number', models.CharField(max_length=50, verbose_name='Número de comprobante')),
                ('total', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Total')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.product')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('payment_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='expense_manager.paymenttype')),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='expense_manager.supplier')),
                ('voucher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='expense_manager.voucher')),
            ],
            options={
                'verbose_name': 'Gasto',
                'verbose_name_plural': 'Gastos',
                'ordering': ['id'],
            },
        ),
    ]
